version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - PORT=${PORT}
        - NODE_ENV=${NODE_ENV}
    user: node
    working_dir: /home/node/app
    env_file:
      - ./.env
    volumes:
      - .:/home/node/app
    ports:
      - ${PORT}:${PORT}
    networks:
      - mynet

networks:
  mynet:

volumes:
  dbdata:
